"""Native-speaker gold pronunciation dictionaries for Mirandese.

Source of truth: https://huggingface.co/datasets/TigreGotico/mirandese_g2p
(``mwl_dataset.tsv``). The word lists are bundled verbatim so the library
works offline; entries keep the dataset's syllable dots, optional-phoneme
parentheses and stress markers.

``GOLD`` maps an ``orthography2ipa`` Mirandese spec code to its gold
dictionary: the base ``mwl`` entries, with dialect-specific overrides layered
on top for ``mwl-x-sendim``. ``RAIANO`` has no matching ``orthography2ipa``
spec and is exposed as a standalone dict only.
"""

CENTRAL: dict = {
    'abandono': 'abɐ̃ˈdonu',
    'abiespra': 'ɐˈbjes̺pɾɐ',
    'adbertido': 'ɐdbɨɾˈtidu',
    'adulto': 'ɐˈdultu',
    'afamado': 'ɐfɐˈmadu',
    'afeito': 'ɐˈfejtʊ',
    'afelhado': 'ɐfɨˈʎadu',
    'alhá': 'ɐˈʎa',
    'alternatibo': 'altɨɾnɐˈtibu',
    'amarielho': 'ɐmɐˈɾjɛʎu',
    'ambesible': 'ɐ̃bɨˈs̺iblɨ',
    'amouchado': 'amowˈtʃaðu',
    'amportante': 'ɐ̃puɾˈtɐ̃tɨ',
    'ampossible': 'ɐ̃puˈsiblɨ',
    'ampressionante': 'ɐ̃pɾɨsjuˈnɐ̃tɨ',
    'anchir': 'ɐ̃ˈtʃiɾ',
    'antender': 'ɐ̃tɨ̃ˈdeɾ',
    'antentar': 'ɐ̃tɨ̃ˈtaɾ',
    'arena': 'ɐˈɾenɐ',
    'açpuis': 'ɐsˈpujs̺',
    'bagaroso': 'bɐɣɐˈɾoz̺ʉ',
    'berde': 'ˈveɾdɨ',
    'bergáncia': 'bɨɾˈɣɐ̃sjɐ',
    'berrugo': 'bɨˈrʉɣʉ',
    'besible': 'bɨˈz̺iblɨ',
    'bexanar': 'bɨʃɐˈnaɾ',
    'bibal': 'biˈβaɫ',
    'bichica': 'biˈt͡ʃikɐ',
    'bielho': 'bjɛʎu',
    'bila de bumioso': 'βila ðɨ βuˈmjo.z̺ʊ',
    'binturiego': 'bĩtʉɾiˈeɣʉ',
    'biolento': 'bjuˈlẽtu',
    'biroç': 'biˈɾos',
    'biuola': 'biˈwolɐ',
    'bizarro': 'biˈzarʉ',
    'biúba': 'biˈuβɐ',
    'boteilha': 'bʉˈtejʎɐ',
    'botin': 'bʉˈtĩŋ',
    'brabo': 'bɾabu',
    'branco': 'bɾɐ̃ku',
    'brando': 'bɾãˈdʉ',
    'brincar': 'bɾĩˈkaɾ',
    'brincote': 'bɾĩˈkote̞',
    'broquin': 'bɾʉˈkĩŋ',
    'broça': 'bɾoˈsɐ',
    'brício': 'ˈbɾisiʉ',
    'brúzio': 'ˈbɾʉziʉ',
    'bubedeiro': 'bʉβɨˈðejɾʉ',
    'bufanda': 'bʉˈfãdɐ',
    'bulda': 'ˈbʉɫdɐ',
    'bulhir': 'bʉˈʎiɾ',
    'bulho': 'ˈbʉʎʉ',
    'bundar': 'bʉ̃ˈdaɾ',
    'buono': 'bwonu',
    'burmeilho': 'buɾˈmɐjʎu',
    'burrada': 'bʉˈraðɐ',
    'buída': 'bʉˈiðɐ',
    'bíblico': 'bibliku',
    'búltio': 'ˈbʉɫtiʉ',
    'cabresto': 'kɐˈbɾeʃtu',
    'calhar': 'kɐˈʎaɾ',
    'canhona': 'kɐˈɲonɐ',
    'cheno': 'ˈtʃenu',
    'chober': 'tʃuˈβeɾ',
    'ciguonha': 's̻iˈɣwoɲɐ',
    'cul': 'kul',
    'dafeito': 'ðɐˈfejtʊ',
    'danho': 'ˈdaɲʉ',
    'defrente': 'dɨˈfɾẽtɨ',
    'defícel': 'dɨˈfisɛl',
    'deimingo': 'dejˈmĩgʊ',
    'douro': 'dowɾʊ',
    'drento': 'ˈdɾẽtu',
    'dóndio': 'dõdiʉ',
    'eigual': 'ɐjˈɡwal',
    'era': 'ˈɛɾɐ',
    'eras': 'ˈɛɾɐs̺',
    'feliç': 'fɨˈlis̻',
    'fierro': 'ˈfjɛru',
    'francesa': 'fɾɐ̃ˈsɛzɐ',
    'francesas': 'fɾɐ̃ˈsɛzɐs̺',
    'franceses': 'fɾɐ̃ˈsɛzɨs̺',
    'francés': 'fɾɐ̃ˈsɛs̺',
    'frauga': 'ˈfɾawɣɐ',
    'freima': 'ˈfɾejmɐ',
    'fui': 'fuj',
    'fumos': 'ˈfumus̺',
    'fuogo': 'fwoɣʊ',
    'fuonte': 'ˈfwõtɨ',
    'fuorte': 'ˈfwɔɾtɨ',
    'fuortemente': 'fwɔɾtɨˈmẽtɨ',
    'fuorça': 'ˈfwɔɾs̻ɐ',
    'fuste': 'ˈfus̺tɨ',
    'fácele': 'ˈfasɨlɨ',
    'grafino': 'ɡɾɐˈfinʉ',
    'guapo': 'ˈɡwapu',
    'haber': 'ɐˈβeɾ',
    'hai': 'aj',
    'home': 'ˈome̞',
    'houmano': 'owˈmɐnu',
    'i': 'i',
    'l': 'l̩',
    'lhabrar': 'ʎɐˈbɾaɾi',
    'lhargo': 'ˈʎaɾɣʉ',
    'lhimpo': 'ˈʎĩpʊ',
    'lhobo': 'ˈʎobʊ',
    'lhuç': 'ˈʎus̻',
    'lhéngua': 'ˈʎɛ̃ɡwɐ',
    'luç': 'ˈʎus̻',
    'macado': 'mɐˈkadu',
    'maias': 'ˈmajɐs̺',
    'mais': 'majs̺',
    'miranda de l douro': 'miˈɾɐ̃dɐ ðɨ l̩ ˈdowɾʊ',
    'mirandés': 'miɾɐ̃ˈdes̺',
    'mogadouro': 'mʊɣɐˈðowɾʊ',
    'molineiro': 'mʊliˈnei̯rʊ',
    'molino': 'muˈlinu',
    'moncas': 'ˈmõkɐs̺',
    'mulhier': 'mʉˈʎjeɾ',
    'muola': 'ˈmu̯olɐ',
    'más': 'mas̺',
    'ne l': 'nɨl',
    'neçairo': 'nɨˈsajɾu',
    'nino': 'ˈninʉ',
    'nuobo': 'ˈnwoβʊ',
    'nó': 'ˈnɔ',
    'n’istante': 'nĩs̺ˈtãte̞',
    'onte': 'ˈõtɨ',
    'oucidental': 'ows̻idẽˈtal',
    'oufecialmente': 'owfɨˌsjalˈmẽtɨ',
    'ourdenhar': 'ou̯ɾdɨˈɲaɾ',
    'oureginal': 'owɾɨʒiˈnal',
    'ourganizaçon': 'ou̯rɡɐnizɐˈsõ',
    'ouropeu': 'owɾuˈpew',
    'ourriêta': 'ˈowrjetɐ',
    'paxarina': 'pɐʃɐˈɾinɐ',
    'pequeinho': 'pɨˈkɐiɲu',
    'perro': 'ˈperʉ',
    'piranha': 'piˈraɲɐ',
    'puis': 'ˈpujs̺',
    'pul': 'ˈpul',
    'puorta': 'ˈpwoɾtɐ',
    'purmeiro': 'puɾˈmɐjɾu',
    'quaije': 'ˈkwajʒɨ',
    'quando': 'ˈkwɐ̃du',
    'quelobrinas': 'kɨluˈbrinas̺',
    'quemun': 'kɨˈmun',
    'rabielho': 'rɐˈβjeʎu',
    'rabudo': 'rɐˈβʉðʉ',
    'ranielha': 'rɐˈnjeʎɐ',
    'rapaziu': 'rɐpɐˈz̻iw',
    'rapaç': 'rɐˈpas̻',
    'rapinar': 'rɐpiˈnaɾ',
    'rata': 'ˈratɐ',
    'rebuolta': 'rɨˈβwoɫtɐ',
    'redegir': 'rɨdɨˈʒiɾ',
    'region de l norte': 'rɨʒiˈõŋ dɐɫ ˈno̝ɾtɨ',
    'remolacha': 'rɨmʊˈlat͡ʃɐ',
    'rico': 'ˈriku',
    'salir': 's̺ɐˈliɾ',
    'screbir': 's̺krɨˈβiɾ',
    'segar': 's̺ɨˈɣaɾ',
    'sendo': 'ˈsẽdu',
    'ser': 'ˈseɾ',
    'sida': 'ˈsidɐ',
    'sidas': 'ˈsidɐs̺',
    'sido': 'ˈsidu',
    'sidos': 'ˈsidus̺',
    'simple': 'ˈs̺ĩplɨ',
    'sobrino': 's̺uˈbɾinu',
    'sodes': 'ˈsodɨs̺',
    'somos': 'ˈsomus̺',
    'son': 'ˈsõ',
    'sou': 'ˈsow',
    'spanha': 'ˈs̺pɐɲɐ',
    'squierdo': 'ˈs̺kjeɾdu',
    'stómado': 'ˈs̺tomɐðʉ',
    'sós': 'ˈs̺ɔs̺',
    'talbeç': 'talˈbes',
    'tamien': 'tɐˈmjẽ',
    'tapabocas': 'tapɐˈbokɐs̺',
    'tascar': 'tɐs̺ˈkaɾ',
    'tener': 'tɨˈneɾ',
    'tierra de miranda': 'ˈtjerɐ ðɨ miˈɾɐ̃dɐ',
    'tierras de miranda': 'ˈtjerɐz̺ ðɨ miˈɾɐ̃dɐ',
    'trasdonte': 'ˈtɾɐz̺dõtɨ',
    'trasdontonte': 'ˈtɾɐz̺dõtõtɨ',
    'trás-ls-muntes': 'tɾaz̺ ɫs̺ ˈmʉ̃tɨs̺',
    'ua': 'ˈũŋɐ',
    'ye': 'ˈje',
    'you': 'jow',
    'yê': 'ˈje',
    'zastre': 'ˈzas̺tɾɨ',
    'zeigual': 'zɐjˈɡwal',
    'zenhar': 'zɨˈɲaɾ',
    'áfrica': 'ˈafɾikɐ',
    'çcansar': 'skɐ̃ˈs̺aɾ',
    'çcrebir': 'skɾɨˈβiɾ',
    'çcriçon': 'skɾiˈsõ',
    'çtinto': 'ˈstĩtu',
    'érades': 'ˈɛɾɐdɨs̺',
    'éramos': 'ˈɛɾɐmus̺',
    'éran': 'ˈɛɾɐn',
    'ũ': 'ˈũ',
    'ũa': 'ˈũŋɐ',
}

SENDINESE: dict = {
    'alhá': 'ɐˈla',
    'deimingo': 'dɨˈmʊ̃j̃.gʊ',
    'demingo': 'dɨˈmʊ̃j̃.gʊ',
    'fuogo': 'fu.ɣʊ',
    'l': 'lʊ',
    'lhobo': 'ˈlo.bʊ',
    'lhuç': 'ˈlus̻',
    'luç': 'ˈlus̻',
    'puorta': 'ˈpuɾtɐ',
    'ye': '(ˈj)i',
    'yê': 'ˈji',
}

RAIANO: dict = {
    'fuogo': 'fwo.ʊ',
    'l': 'ɐl',
}

GOLD: dict = {
    "mwl": CENTRAL,
    "mwl-x-sendim": {**CENTRAL, **SENDINESE},
    "mwl-x-ifanes": CENTRAL,
}
